"""Название миграции

Revision ID: 01e29ad56a2f
Revises: eb02df12a16a
Create Date: 2024-12-29 23:33:12.384511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e29ad56a2f'
down_revision = 'eb02df12a16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
