"""Название миграци

Revision ID: 98cb3d8138e2
Revises: 0d8b40ac15ce
Create Date: 2025-01-09 18:52:58.359213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98cb3d8138e2'
down_revision = '0d8b40ac15ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
