"""Название миграции

Revision ID: 383c8748ad0a
Revises: aa5a0074ecad
Create Date: 2024-12-28 15:18:40.529870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383c8748ad0a'
down_revision = 'aa5a0074ecad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
