"""Название миграци

Revision ID: 9397781a68f1
Revises: fefadc2d6748
Create Date: 2025-01-05 14:08:13.770817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9397781a68f1'
down_revision = 'fefadc2d6748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
