"""Название миграции

Revision ID: ae0caebc1f4e
Revises: c933866880f9
Create Date: 2024-12-30 15:16:23.843395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0caebc1f4e'
down_revision = 'c933866880f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
