"""Название миграции

Revision ID: c933866880f9
Revises: be8b214be31a
Create Date: 2024-12-30 15:08:47.596626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c933866880f9'
down_revision = 'be8b214be31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
