"""Название миграции

Revision ID: eb02df12a16a
Revises: eedc3a060c0f
Create Date: 2024-12-29 23:21:29.021506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb02df12a16a'
down_revision = 'eedc3a060c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
