"""Название миграции

Revision ID: eedc3a060c0f
Revises: be8b214be31a
Create Date: 2024-12-29 23:21:07.574724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedc3a060c0f'
down_revision = 'be8b214be31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
