"""Название миграции

Revision ID: f7c9bcc820f4
Revises: ae0caebc1f4e
Create Date: 2024-12-30 15:39:39.280070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c9bcc820f4'
down_revision = 'ae0caebc1f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
