"""Название миграции

Revision ID: fefadc2d6748
Revises: f7c9bcc820f4
Create Date: 2024-12-30 15:43:58.550704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefadc2d6748'
down_revision = 'f7c9bcc820f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
